pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
               git branch: 'main', 
                   credentialsId: '96ede419-74f7-4d89-88a3-f44d62c141b1', 
                   url: 'https://github.com/shivaprasadmullapudi/Jenkins-Zero-To-Hero'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t shivaprasadmullapudi359/dockerrepo:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push shivaprasadmullapudi359/dockerrepo:${BUILD_NUMBER}
                    '''
                }
            }
        }
        }
    }
}
